name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Make gradlew executable
        run: chmod +x ./app/gradlew
      
      - name: Execute Gradle build
        run: |
          cd app
          ./gradlew build
          ./gradlew checkstyleMain
          ./gradlew checkstyleTest
      
      - name: Execute Gradle build with Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd app
          ./gradlew build jacocoTestReport checkstyleMain checkstyleTest sonar --info